export const GLOBAL_DEFAULTS = {
  fontSize: 20,
  fontColor: '#000000',
  font: 'NunitoSans',
  bold: false,
  italic: false,
  underline: false,
  backgroundColor: 'transparent',
  width: 180,
  height: 60,
  xPosition: 0,
  yPosition: 0,
  zIndex: 0,
  isRelevantForPresentationComplete: undefined,
  loop: false,
  startControl: true,
  pauseControl: false,
  progressBar: true,
  interactiveProgressbar: false,
  volumeControl: true,
  defaultVolume: 0.8,
  minVolume: 0.2,
  muteControl: true,
  interactiveMuteControl: false,
  hintLabel: 'Bitte starten',
  minRuns: 1,
  maxRuns: 1,
  showRestRuns: false,
  showRestTime: true,
  playbackTime: 0
};

export const ELEMENT_DEFAULTS: Record<string, Record<string, unknown>> = {
  text: {
    text: 'Lorem ipsum dolor sit amet',
    markingMode: 'selection',
    markingPanels: [],
    highlightableOrange: false,
    highlightableTurquoise: false,
    highlightableYellow: false,
    hasSelectionPopup: false,
    columnCount: 1,
    height: 98,
    marginBottom: { value: 10, unit: 'px' },
    lineHeight: 135
  },
  button: {
    label: 'Knopf',
    imageSrc: null,
    asLink: false,
    action: null,
    actionParam: null,
    tooltipText: '',
    tooltipPosition: 'below',
    labelAlignment: 'baseline',
    backgroundColor: 'lightgrey'
  },
  'text-field': {
    appearance: 'outline',
    minLength: null,
    minLengthWarnMessage: 'Eingabe zu kurz',
    maxLength: null,
    maxLengthWarnMessage: 'Eingabe zu lang',
    isLimitedToMaxLength: true,
    pattern: null,
    patternWarnMessage: 'Eingabe entspricht nicht der Vorgabe',
    clearable: false,
    required: false,
    requiredWarnMessage: 'Eingabe erforderlich',
    readOnly: false,
    width: 180,
    height: 120,
    lineHeight: 135,
    inputAssistancePreset: null,
    inputAssistancePosition: 'floating',
    inputAssistanceFloatingStartPosition: 'startBottom',
    showSoftwareKeyboard: false,
    addInputAssistanceToKeyboard: false,
    hideNativeKeyboard: false,
    keyStyle: 'round',
    hasArrowKeys: false,
    inputAssistanceCustomKeys: '',
    inputAssistanceCustomStyle: 'medium',
    restrictedToInputAssistanceChars: false,
    hasBackspaceKey: false
  },
  'text-field-simple': {
    minLength: null,
    minLengthWarnMessage: 'Eingabe zu kurz',
    maxLength: null,
    maxLengthWarnMessage: 'Eingabe zu lang',
    isLimitedToMaxLength: true,
    pattern: null,
    patternWarnMessage: 'Eingabe entspricht nicht der Vorgabe',
    clearable: false,
    backgroundColor: '#f1f1f1',
    width: 100,
    height: 30,
    lineHeight: 135,
    inputAssistancePreset: null,
    inputAssistancePosition: 'floating',
    inputAssistanceFloatingStartPosition: 'startBottom',
    showSoftwareKeyboard: false,
    addInputAssistanceToKeyboard: false,
    hideNativeKeyboard: false,
    keyStyle: 'round',
    hasArrowKeys: false,
    inputAssistanceCustomKeys: '',
    inputAssistanceCustomStyle: 'medium',
    restrictedToInputAssistanceChars: false,
    hasBackspaceKey: false
  },
  'text-area': {
    appearance: 'outline',
    resizeEnabled: false,
    hasDynamicRowCount: true,
    hasAutoHeight: false,
    rowCount: 3,
    expectedCharactersCount: 135,
    hasReturnKey: false,
    width: 230,
    height: 132,
    lineHeight: 135,
    inputAssistancePreset: null,
    inputAssistancePosition: 'floating',
    inputAssistanceFloatingStartPosition: 'startBottom',
    showSoftwareKeyboard: false,
    addInputAssistanceToKeyboard: false,
    hideNativeKeyboard: false,
    keyStyle: 'round',
    hasArrowKeys: false,
    inputAssistanceCustomKeys: '',
    inputAssistanceCustomStyle: 'medium',
    restrictedToInputAssistanceChars: false,
    hasBackspaceKey: false
  },
  checkbox: {
    label: 'Beschriftung',
    imgSrc: null,
    value: false,
    required: false,
    requiredWarnMessage: 'Eingabe erforderlich',
    readOnly: false,
    crossOutChecked: false,
    width: 215,
    height: 60
  },
  dropdown: {
    options: [],
    allowUnset: false,
    width: 240,
    height: 83
  },
  radio: {
    options: [],
    label: 'Beschriftung',
    alignment: 'column',
    strikeOtherOptions: false,
    width: 215,
    height: 80
  },
  image: {
    src: null,
    alt: 'Bild nicht gefunden',
    scale: false,
    allowFullscreen: false,
    magnifier: false,
    magnifierSize: 100,
    magnifierZoom: 1.5,
    magnifierUsed: false,
    fileName: '',
    width: 180,
    height: 100,
    marginBottom: { value: 15, unit: 'px' }
  },
  audio: {
    src: null,
    fileName: '',
    width: 180,
    height: 90,
    marginBottom: { value: 15, unit: 'px' },
    backgroundColor: '#f1f1f1'
  },
  video: {
    src: null,
    fileName: '',
    scale: false,
    width: 280,
    height: 230,
    marginBottom: { value: 15, unit: 'px' },
    backgroundColor: '#f1f1f1'
  },
  cloze: {
    document: {
      type: 'doc',
      content: [{
        type: 'paragraph',
        attrs: {
          textAlign: 'left',
          indent: null,
          indentSize: 20,
          hangingIndent: false,
          margin: 0
        },
        content: [
          {
            text: 'Lorem Ipsum',
            type: 'text'
          }
        ]
      }]
    },
    columnCount: 1,
    width: 180,
    height: 200,
    marginBottom: { value: 35, unit: 'px' },
    lineHeight: 180
  },
  'marking-panel': {
    highlightableYellow: true,
    highlightableTurquoise: false,
    highlightableOrange: false,
    width: 180,
    height: 98,
    marginBottom: { value: 10, unit: 'px' }
  },
  slider: {
    minValue: 0,
    maxValue: 100,
    showValues: true,
    barStyle: 'default',
    thumbLabel: 'always',
    width: 240,
    height: 80,
    lineHeight: 5
  },
  'spell-correct': {
    width: 230,
    height: 80,
    lineHeight: 135,
    inputAssistancePreset: null,
    inputAssistancePosition: 'floating',
    inputAssistanceFloatingStartPosition: 'startBottom',
    showSoftwareKeyboard: false,
    addInputAssistanceToKeyboard: false,
    hideNativeKeyboard: false,
    keyStyle: 'round',
    hasArrowKeys: false,
    inputAssistanceCustomKeys: '',
    inputAssistanceCustomStyle: 'medium',
    restrictedToInputAssistanceChars: false,
    hasBackspaceKey: false
  },
  frame: {
    width: 180,
    height: 180,
    zIndex: -1,
    hasBorderTop: true,
    hasBorderBottom: true,
    hasBorderLeft: true,
    hasBorderRight: true,
    borderWidth: 1,
    backgroundColor: 'transparent'
  },
  'toggle-button': {
    options: [{ text: 'Option A' }, { text: 'Option B' }],
    strikeOtherOptions: false,
    strikeSelectedOption: false,
    verticalOrientation: false,
    selectionColor: '#c9e0e0',
    width: 180,
    height: 30,
    lineHeight: 100
  },
  geometry: {
    appDefinition: '',
    fileName: '',
    height: 400,
    width: 600,
    showResetIcon: true,
    enableUndoRedo: true,
    showToolbar: true,
    enableShiftDragZoom: false,
    showZoomButtons: false,
    showFullscreenButton: false,
    customToolbar: '',
    trackedVariables: [],
    trackedExpectedVariables: []
  },
  'hotspot-image': {
    src: null,
    fileName: '',
    value: [],
    width: 250,
    height: 100
  },
  'math-field': {
    width: 230,
    height: 80,
    lineHeight: 135,
    enableModeSwitch: false,
    mathKeyboardPresets: ['math', 'symbols', 'latin', 'greek'],
    required: false,
    requiredWarnMessage: 'Eingabe erforderlich',
    readOnly: false
  },
  'math-table': {
    width: 230,
    height: 192,
    operation: 'addition',
    terms: ['123', '456'],
    result: '',
    resultHelperRow: '',
    inputAssistancePreset: null,
    inputAssistancePosition: 'floating',
    inputAssistanceFloatingStartPosition: 'startBottom',
    showSoftwareKeyboard: false,
    addInputAssistanceToKeyboard: false,
    keyStyle: 'round',
    hideNativeKeyboard: false,
    hasArrowKeys: false,
    variableLayoutOptions: {
      allowArithmeticChars: false,
      isFirstLineUnderlined: true,
      showResultRow: false,
      showTopHelperRows: false,
      allowFirstLineCrossOut: false
    },
    helperRowColor: 'transparent'
  },
  'text-area-math': {
    width: 230,
    height: 132,
    lineHeight: 135
  },
  trigger: {
    action: null,
    actionParam: null,
    width: 20,
    height: 20
  },
  table: {
    width: 250,
    height: 200,
    gridColumnSizes: [{ value: 1, unit: 'fr' }, { value: 1, unit: 'fr' }],
    gridRowSizes: [{ value: 1, unit: 'fr' }, { value: 1, unit: 'fr' }],
    elements: [],
    tableEdgesEnabled: false,
    marginBottom: 30,
    borderWidth: 1,
    backgroundColor: 'transparent'
  },
  'radio-group-images': {
    options: [],
    label: 'Beschriftung',
    itemsPerRow: null,
    width: 250,
    height: 200
  },
  'drop-list': {
    value: [],
    width: 240,
    height: 100,
    minHeight: 57,
    isSortList: false,
    onlyOneItem: false,
    connectedTo: [],
    copyOnDrop: false,
    allowReplacement: false,
    orientation: 'vertical',
    showNumbering: false,
    startNumberingAtZero: false,
    highlightReceivingDropList: false,
    highlightReceivingDropListColor: '#006064',
    permanentPlaceholders: false,
    permanentPlaceholdersCC: false,
    backgroundColor: '#ededed',
    itemBackgroundColor: '#c9e0e0'
  },
  'likert-row': {
    rowID: '',
    rowLabel: {
      text: '', imgSrc: null, imgFileName: '', imgPosition: 'above'
    },
    columnCount: 0,
    firstColumnSizeRatio: 5,
    verticalButtonAlignment: 'center',
    height: 50
  },
  likert: {
    rows: [],
    options: [],
    firstColumnSizeRatio: 5,
    label: 'Optionentabelle Beschriftung',
    label2: 'Beschriftung Erste Spalte',
    stickyHeader: false,
    width: 250,
    height: 200,
    marginBottom: { value: 35, unit: 'px' },
    lineHeight: 135,
    backgroundColor: 'white',
    lineColoring: true,
    lineColoringColor: '#c9e0e0',
    firstLineColoring: false,
    firstLineColoringColor: '#c7f3d0'
  },
  'widget-calc': {
    mode: 'SIMPLE',
    journalLines: 0,
    state: null,
    backgroundColor: '#f1f1f1',
    fontColor: '#006064'
  },
  'widget-molecule-editor': {
    bondingType: 'VALENCE',
    state: null,
    backgroundColor: '#f1f1f1',
    fontColor: '#006064'
  },
  'widget-periodic-table': {
    showInfoOrder: true,
    showInfoENeg: false,
    showInfoAMass: true,
    closeOnSelection: false,
    maxNumberOfSelections: 1,
    state: null,
    backgroundColor: '#f1f1f1',
    fontColor: '#006064'
  }
};
