# Image for building and testing the app

FROM node:22-bookworm

RUN apt update && apt install -y chromium curl jq \
 libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
